# Use EAP 6.1.1/RHEL7 Base Image for Hello World Build/Test/Delployment
FROM eap-jdk1.6-rhel7

# Copy WAR file to EAP Deployment Directory
ADD eaphelloworldv100-1.02.war /opt/jboss/jboss-eap-6.1/standalone/deployments/
