FROM rhel6-base
MAINTAINER Greg Hoelzer ghoelzer@redhat.com

# Update the image (using an employee subscription)  
RUN subscription-manager register --username=account  --password='password' --auto-attach  
RUN subscription-manager repos --disable=*  
RUN subscription-manager repos --enable rhel-6-server-rpms  

# Execute system update
RUN yum -y update && yum clean all

# Install Apache Maven
RUN yum -y install wget
RUN wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
RUN sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
RUN yum install -y apache-maven
RUN mvn --version

# Install packages necessary to run EAP
RUN yum -y install saxon unzip && yum clean all

# Create a user and group used to launch processes
# The user ID 1000 is the default for the first "regular" user on Fedora/RHEL,
# so there is a high chance that this ID will be equal to the current user
# making it easier to use volumes (no permission issues)
RUN groupadd -r jboss -g 1000 && useradd -u 1000 -r -g jboss -m -d /opt/jboss -s /sbin/nologin -c "JBoss user" jboss

# Set the working directory to jboss' user home directory
WORKDIR /opt/jboss

# Specify the user which should be used to execute all commands below
USER jboss

