# Use EAP 6.1.1/RHE6 Base Image for Hello World Build/Test/Delployment
FROM eap-jdk1.7-rhel6

# Copy WAR file to EAP Deployment Directory
ADD eaphelloworldv100-1.02.war $JBOSS_HOME/standalone/deployments/
