# Use EAP 6.1.1/RHEL7 Base Image for Hello World Build/Test/Delployment
FROM jbosseap611/7

# Updated App to version 1.02

USER root

# Copy WAR file to EAP Deployment Directory
ADD eaphelloworldv100-1.02.war /opt/jboss/eap-6.1/standalone/deployments/

USER jboss


